<!DOCTYPE html>
<html>
  <head>
    <title>prueba php html</title>
  </head>
  
  <body>


<form method='POST'>
	<div class="form-group">
		<label for="nombre">Nombre</label>
		<input type="text" class="form-control" name='nombre' id="nombre" placeholder="nombre...">
	</div>
	<div class="form-group">
		<label for="email">Email</label>
		<input type="email" class="form-control" name='email' id="email" placeholder="email...">
	</div>
	<div class="form-group">
		<label for="exampleTextarea">Mensaje</label>
		<textarea class="form-control" name='mensaje' id="mensaje" rows="3"></textarea>
	</div>
	<div class="form-group">
		<input type="checkbox" required> Acepto la política de privacidad.
	</div>
	<button class="btn btn-primary" type="submit">Enviar</button>
</form>
<?php 
                          $nombre = $_POST['nombre'];
                          $email = $_POST['email'];
                          $asunto = 'Formulario Rellenado';
                          $mensaje = "Nombre: ".$nombre."<br> Email: $email<br> Mensaje:".$_POST['mensaje'];


                          if(mail('tuEmail', $asunto, $mensaje)){
                            echo "Correo enviado";
                          }(o nombre del archivo de proceso)
                         ?>

                     </body>
                     </html>